### ISSUE TITLE
Best order of videos

### ISSUE THREAD

**Issue by AllThingsSmitty** [AllThingsSmitty/must-watch-css#1]
Should I add the videos in chronological order or assign the order based on video rating/popularity?

The videos are already ordered by year which is optimal and won't change. Should I order the videos within that year by descending order? Ordering based on popularity (number of likes) requires more overhead and isn't automated. The only other viable suggestion is to just add the video at the of the year's list.

**Comment by AllThingsSmitty** [comment]
I've been rethinking this...

In order of "must-watch-ness" has been pretty much how I've been going but still wonder if there is a benefit of chronological order. Feedback is welcome.

**Comment by marcobiedermann** [comment]
Why not add subcategories like "Architecture", "Performance", "Secrets", "UI / UX" and than sort them by date. This way we would provide a better guideline for beginners.

**Comment by AllThingsSmitty** [comment]
@marcobiedermann that's an interesting idea. Sub-cats within each year?

**Comment by KleoPetroff** [comment]
Isn't it better to use the type of videos (Architecture, Performance etc.) as a main category and years as a sub-categories.

**Comment by marcobiedermann** [comment]
@AllThingsSmitty No, the other way around like @KleoPetroff mentioned

## Architecture
* Video by date
* Video by date
* Video by date

## Performance
* Video by date
* Video by date
