### ISSUE TITLE
Description update

### ISSUE THREAD

**Issue by davupls** [AllThingsSmitty/must-watch-css#16]
Collection of well-received talks about CSS, covering CSS Grid, flexbox, frameworks, variables, Sass, SVG, performance, tooling, and more.

- [✅] Right to the point.

**Comment by AllThingsSmitty** [comment]
Thanks for the suggestion. I agree that's right to the point. Let me think about that.

**Comment by davupls** [comment]
Thanks for taking the time out to consider. I'm a rookie in the coding world.
