### ISSUE TITLE
Missing a license

### ISSUE THREAD

**Issue by arthurvr** [AllThingsSmitty/must-watch-css#8]
This repo seems to miss a license. Check https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license :)

**Comment by AllThingsSmitty** [comment]
@arthurvr that's a good idea. I wasn't sure where this is a list of copyrighted videos that would work, but since it's more about the list itself that should be fine.

**Comment by AllThingsSmitty** [comment]
Commit [18337cc](https://github.com/AllThingsSmitty/must-watch-css/commit/18337cc60d83b092edcf33cad2413e366e74580e)
